; Sample ddos_checker.ini file

; Path to Apache logs directory
nginx_logs_path=/var/log/virtualmin

; Path to nginx ip blocklist (for firewall use)
nginx_blocklist=/home/user/public_html/nginx_blocklist.txt

; Path to nginx cidr blocklist (for Nginx Bad Bot Blocker use)
nginx_cidr_blocklist=/etc/nginx/snippets/nginx_cidr_blocklist.conf

; Comma-separated list of domains to exclude from checking
excluded_domains=example.com,subdomain.example.com

; Comma-separated list of ips to exclude from checking
excluded_ips=1.2.3.4

; Timeframe in minutes to check for DDoS attacks
timeframe=15

; Threshold for the number of requests per IP to consider as a potential DDoS attack
threshold=100

; Additional threshold for the number of requests per IP to consider as a potential DDoS attack
additional_threshold=1000

; Additional timeframe in minutes to check for DDoS attacks
additional_timeframe=5

; Bantime in seconds to ban in in csf firewall
bantime=3600

; AbuseIPDB
; Set your AbuseIPDB API key here.
abuseipdb_token=/root/.tokens/.abuseipdb-token
abuseipdb_report=true
abuseipdb_log_folder=/var/log/abuseipdb
abuseipdb_bulk_report_interval=1hour